algoritmo "Algoritmo5"
// Função :
// Autor :
// Data : 05/09/2018
// Seção de Declarações 
var
AnoNasc, AnoAtual, Idade: inteiro
inicio
escreva("Informe seu ano de nascimento:")
leia(AnoNasc)
escreva("Informe o ano atual:")
leia(AnoAtual)
Idade <- AnoAtual - AnoNasc
se(Idade >= 18)entao
escreva("Você é maior de idade")
senao
escreva("Você é menor de idade")
fimse
// Seção de Comandos 
fimalgoritmo
