algoritmo "Algoritmo ex5"
// Função :
// Autor :
// Data : 01/01/2007
// Seção de Declarações 
var
dependentes :inteiro
vhora1,vhora2,bruto,liquido :real
inicio
// Seção de Comandos 
escreva ("Informe o número de depenfentes:")
leia (dependentes)
escreva ("Digite o custo por hora do seu trabalho:")
leia (vhora1)
bruto <- vhora1*vhora2
liquido <- (dependentes * 300) + bruto
escreva ("O valor de seu salario bruto é:",bruto)
escreva ("O valor de seu salario liquido é:",Liquido)

fimalgoritmo
